# {{platform_display}} — CrawlHub Platform Crawler

> Auto-generated by `crawlhub platform new {{platform_name}}`.
> Edit this README to document **your** platform once you've replaced the
> `ping` placeholder action.

---

## What you just got

```
crawlhub/crawlers/{{platform_name}}/
├── __init__.py
├── plugin.yaml              # manifest — declares actions & schemas
├── service.py               # dispatch layer (R3: keep thin)
├── README.md                # this file
└── crawler/
    ├── __init__.py          # public entry point: re-exports {{scraper_class}}
    ├── scraper.py           # business orchestration (yields dicts)
    ├── client.py            # HTTP / network layer
    ├── models.py            # @dataclass + to_dict()
    └── _internal/           # platform-private helpers (sealed by R3)
        └── __init__.py
```

The generated scaffold ships with one trivial action — `ping` — purely so
that `pytest tests/test_platform_conformance.py` passes immediately. Your
first real edits should:

1. Add your real actions to `plugin.yaml` (replace `ping`).
2. Choose each action's `runtime`, `transport`, and `throttle_scope`.
3. Add matching `@dataclass` types to `crawler/models.py`.
4. Implement those actions as public methods on `{{scraper_class}}`
   (`crawler/scraper.py`), each writing `Model(...).to_dict()`.
5. Move network protocol details into `crawler/client.py`.

---

## Three-layer responsibility (R3)

| Layer       | File                       | MUST do                                                                 | MUST NOT do                                          |
|-------------|----------------------------|-------------------------------------------------------------------------|------------------------------------------------------|
| Service     | `service.py`               | Instantiate scraper, dispatch action, pass `(ctx, params)` through       | Network, schema mapping, import `crawler._internal.*`|
| Scraper     | `crawler/scraper.py`       | Pagination, merge, iteration, write via `ctx.write_record(Model.to_dict())` | HTTP, signing, cookie parsing                        |
| Client      | `crawler/client.py`        | HTTP/WSS protocol work, signing, cookie injection, single-request/client retries | Multi-request orchestration, schema mapping          |
| Models      | `crawler/models.py`        | `@dataclass`, `from_raw()` helpers, `to_dict()`                         | Network calls, `TaskContext` access                  |
| `_internal/`| `crawler/_internal/*`      | Platform-private helpers (cookie / sign / parse)                        | Be imported from `service.py` / `bridge.py`          |

---

## ⚠️ Action method signature — MUST READ

Every action method on `{{scraper_class}}` MUST have this exact signature:

```python
def <action_name>(self, ctx: TaskContext, params: dict) -> None:
    app_id    = params["app_id"]                # required key
    max_pages = params.get("max_pages", 10)     # optional, with default
    ...
    ctx.write_record(record.to_dict())
    ctx.set_progress(1.0)
```

**DO NOT do this:**

```python
# ❌ WRONG — will crash at runtime with TypeError
def my_action(self, ctx, app_id: str, max_pages: int = 10) -> None: ...

# in service.py:
method(ctx, **params)  # ❌ unpacks every key as a kwarg
```

### Why

The CrawlHub platform (daemon + routes) injects **control flags** into a
task's params dict — currently `treat_empty_as_success`, and we will add
more over time (rate-limit overrides, retry policies, telemetry tags…).
These are NOT business inputs.

If you unpack `**params` into named kwargs, Python raises:

```
TypeError: my_action() got an unexpected keyword argument
           'treat_empty_as_success'
```

…and the task fails immediately, even though the scraper logic is fine.

`params.get("name", default)` and `params["required_name"]` naturally
ignore any extra keys, which is the desired behavior. This is the
project-wide convention — every existing crawler follows it.

### Tooling

`tests/test_platform_conformance.py` checks that scraper methods follow
this contract. If you see an error like `C11: action 'X' uses **params
unpack` (or similar), this is what it's pointing at.

---

## Action runtime / transport quick guide

Use these combinations in `plugin.yaml`:

| Scenario | runtime | transport | throttle_scope |
|----------|---------|-----------|----------------|
| Plain HTTP task | `stateless` | `http` | `task` |
| Browser-backed HTTP request | `browser_backed` | `http` | `request` |
| Pure Python WebSocket | `stateless` | `websocket` | `none` |
| Browser-assisted WebSocket bootstrap | `browser_backed` | `websocket` | `none` |

R7 注：`lease_policy` 字段已被删除。所有 BBA action 走统一 hold 模型——
scraper 通过 `with self.runtime.browser.hold() as page:` 拿独占 page；
退出 with 即关 page；最后一个 page 关时升级关 chrome。

For every `transport: websocket` action, expose both stop inputs:

```yaml
duration_seconds:
  type: integer
  default: 60
stop_when_room_closed:
  type: boolean
  default: true
```

WebSocket actions should end when `duration_seconds` is reached, or when
`stop_when_room_closed` is enabled and the platform reports the room is closed.

---

## How CrawlHub finds and registers `{{platform_name}}`

1. At daemon startup, `crawlhub.core.registry.discover_platforms()` scans
   `crawlhub/crawlers/*/plugin.yaml`.
2. `plugin.yaml` is parsed and validated against the rules R4–R7.
3. For every action with `output_dataclass: module:Class`, R7 checks
   `dataclass.fields() == output_schema.keys()` (minus synthetic
   `_source_*` columns).
4. `entry: "crawlhub.crawlers.{{platform_name}}.service:{{service_class}}"`
   is imported via `importlib.import_module`, verified to subclass
   `BasePlatformService`, and registered.
5. When a task arrives, the daemon calls
   `{{service_class}}().execute(action, params, ctx)`.

You do not need to register anything explicitly — the directory layout
**is** the registration.

---

## TaskContext API (available inside `service.py`)

| Method                       | Purpose                                                        |
|------------------------------|----------------------------------------------------------------|
| `ctx.write_record(dict)`     | Emit a record (keys MUST match `plugin.yaml` `output_schema`)  |
| `ctx.set_progress(0.0..1.0)` | Update progress (visible in the web UI)                         |
| `ctx.log(str)`               | Append a task-scoped log line                                   |
| `ctx.output_dir`             | Per-task temp directory (use this instead of package paths)     |

To consume a cookie (when `plugin.yaml` `cookie.required: true`):

```python
from crawlhub.core.cookie_override import get_thread_cookie_override
cookie_path = get_thread_cookie_override()
```

---

## Verifying your changes

Run any of these any time — they're cheap:

```bash
# Static contract check (all platforms)
python tests/test_platform_conformance.py

# Just this one
python tests/test_platform_conformance.py --platform {{platform_name}}

# pytest-driven (CI gate)
pytest tests/test_platform_conformance.py -k {{platform_name}}

# Shape / schema check
python -m crawlhub.scripts.verify_crawlers --only {{platform_name}}
```

A green run means your crawler obeys the platform conformance gate,
including schema/dataclass matching, service thinness, runtime/transport
metadata, and WebSocket stop-condition contracts. The daemon will register
it on next start.

---

## Common errors and what they mean

| Error                                                                | Cause                                                          | Fix                                                            |
|----------------------------------------------------------------------|----------------------------------------------------------------|----------------------------------------------------------------|
| `C2: action='X' is missing output_dataclass`                         | New action added to yaml without `output_dataclass`            | Add `output_dataclass: "<your.models>:Class"`                  |
| `C3: action='X' field mismatch`                                      | Dataclass fields drifted from `output_schema`                  | Make them equal (modulo `_source_*`)                           |
| `C4/C5: imports from crawler._internal.*`                            | `service.py` / `bridge.py` reaches into private helpers        | Re-export the helper via `crawler/__init__.py`                 |
| `C6: forbidden directory 'output/'` (etc.)                           | You wrote artifacts into the package tree                      | Use `ctx.output_dir` instead                                   |
| `C7: ctx.write_record(asdict(...))` / inline-dict write              | Bypassing the dataclass contract                               | Build a `@dataclass`, call `.to_dict()` on it                  |
| `C8: dataclass ... has no to_dict()`                                 | New dataclass forgot the method                                | Add a `def to_dict(self) -> dict:` returning `asdict(self)`    |
| `C9: ... Path(__file__) together with a write API`                   | Writing inside the package                                     | Switch to `ctx.output_dir` or `get_data_root()`                |
| `C10: yaml declares actions [...] but service.py does not dispatch`  | You added a yaml action without a matching scraper method      | Add the method (`getattr` dispatch handles the rest)           |
| `C21: transport=websocket must declare ...`                         | WSS action lacks explicit stop inputs                          | Add `duration_seconds` and `stop_when_room_closed` inputs      |
